import csv
import os


RESULT_CSV = os.path.join("results", "adaptive_ivfpq_20260630.csv")
OUT_PATH = os.path.join("fig", "adaptive_recall_latency.tex")

LABELS = {
    "fixed_low_np2_p500": "fixed 2/500",
    "fixed_mid_np4_p1000": "fixed 4/1000",
    "fixed_near_np5_p1000": "fixed 5/1000",
    "fixed_high_np8_p1500": "fixed 8/1500",
    "adaptive_conservative": "cons.",
    "adaptive_aggressive": "aggr.",
    "adaptive_recall_oriented": "recall",
    "adaptive_conservative_grouped": "cons.+grp",
}

FIXED = {
    "fixed_low_np2_p500",
    "fixed_mid_np4_p1000",
    "fixed_near_np5_p1000",
    "fixed_high_np8_p1500",
}


def scale_x(latency):
    return (latency - 140.0) / (350.0 - 140.0) * 11.0


def scale_y(recall):
    return (recall - 0.86) / (1.00 - 0.86) * 5.0


def main():
    rows = []
    with open(RESULT_CSV, newline="", encoding="utf-8") as fin:
        for row in csv.DictReader(fin):
            if row["method"] in LABELS:
                rows.append(row)

    found = {row["method"] for row in rows}
    missing = sorted(set(LABELS) - found)
    if missing:
        raise RuntimeError("missing adaptive rows: " + ", ".join(missing))

    rows.sort(key=lambda row: float(row["latency_us"]))
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as out:
        out.write("% Generated by gen_adaptive_fig.py from adaptive_ivfpq_20260630.csv\n")
        out.write("\\begin{tikzpicture}[font=\\scriptsize]\n")
        out.write("  \\draw[->,thick] (0,0) -- (11.7,0) node[right] {Latency (us/query)};\n")
        out.write("  \\draw[->,thick] (0,0) -- (0,5.45) node[above] {Recall@10};\n")
        for tick in [150, 200, 250, 300, 350]:
            x = scale_x(tick)
            out.write(f"  \\draw ({x:.2f},0) -- ({x:.2f},-0.08) node[below] {{{tick}}};\n")
        for tick in [0.86, 0.90, 0.94, 0.98, 1.00]:
            y = scale_y(tick)
            out.write(f"  \\draw (0,{y:.2f}) -- (-0.08,{y:.2f}) node[left] {{{tick:.2f}}};\n")
        out.write("  \\draw[black!15] (0,0) grid[xstep=2.619,ystep=1.428] (11,5);\n")
        for row in rows:
            method = row["method"]
            x = scale_x(float(row["latency_us"]))
            y = scale_y(float(row["recall_at_10"]))
            label = LABELS[method]
            if method in FIXED:
                out.write(f"  \\fill[blue!65] ({x:.2f},{y:.2f}) circle (2.2pt);\n")
            elif method == "adaptive_conservative_grouped":
                out.write(
                    f"  \\node[star,star points=5,fill=red!70,draw=black,"
                    f"inner sep=1.1pt] at ({x:.2f},{y:.2f}) {{}};\n")
            else:
                out.write(
                    f"  \\draw[fill=green!65!black,draw=black] "
                    f"({x - 0.06:.2f},{y - 0.06:.2f}) rectangle "
                    f"({x + 0.06:.2f},{y + 0.06:.2f});\n")
            out.write(
                f"  \\node[anchor=west] at ({x + 0.10:.2f},{y + 0.08:.2f})"
                f" {{{label}}};\n")
        out.write("  \\fill[blue!65] (7.45,0.65) circle (2.2pt);"
                  " \\node[anchor=west] at (7.62,0.65) {fixed};\n")
        out.write("  \\draw[fill=green!65!black,draw=black] (7.39,0.32) rectangle (7.51,0.44);"
                  " \\node[anchor=west] at (7.62,0.38) {adaptive};\n")
        out.write("  \\node[star,star points=5,fill=red!70,draw=black,inner sep=1.1pt]"
                  " at (7.45,0.12) {};"
                  " \\node[anchor=west] at (7.62,0.12) {adaptive+grouped};\n")
        out.write("\\end{tikzpicture}\n")
    print(OUT_PATH)


if __name__ == "__main__":
    main()
